### ISSUE TITLE
Section data view disregards FileAlignment

### ISSUE THREAD

**Issue by eternaleclipse** [hasherezade/pe-bear#11]
When displaying section data, PE-Bear uses `IMAGE_SECTION_HEADER.PointerToRawData` to find the section data in the file. In reality, when Windows loads the file, if the section file offset is not aligned to `IMAGE_OPTIONAL_HEADER.FileAlignment`, it will be rounded up to the next aligned address and loaded there. A malicious binary can use this inconsistency to display incorrect section data.

Btw, CFF Explorer falls for this too. IDA Pro displays a warning that it has detected a section that is not aligned and refuses to handle the section header.

Screenshot demonstrating the difference in section contents between section data in PE-Bear and what is actually loaded in memory (x64dbg):
![Screenshot 2022-10-22 024856](https://user-images.githubusercontent.com/12075301/197305976-5d324630-c8e0-4304-8a50-aa0eacaeb597.png)

EXE for reproduction: [packed.zip](https://github.com/hasherezade/pe-bear/files/9843073/packed.zip)

**Comment by eternaleclipse** [comment]
btw version is `PE-bear_0.6.1_x64_win_vs17` (latest)

**Comment by hasherezade** [comment]
@eternaleclipse  - I fixed it, would you like to test the new version pre-release? you can download the builds from AppVeyor server, as described in the [README](https://github.com/hasherezade/pe-bear#builds).
I will appreciate your feedback.

**Comment by eternaleclipse** [comment]
Having automatic builds from build is so convenient!
I'm checking it out now.

**Comment by eternaleclipse** [comment]
Looks great! It shows the correct mapped offset now for the code section.

A few suggestions:
- Adding an additional warning during loading, if the `IMAGE_SECTION_HEADER.PointerToRawData` is misaligned.
- Changing the names to something more indicative, like "Raw Offset (file)", "Mapped offset (file)", "Virtual address (mem)".
- The current build fixes Section headers and Code views. I haven't tested, but I suspect the bug will resurface in any section type that contains pointers (imports, exports, relocations, etc). There might be some fixing required with the "Follow raw" behaviour to point to the actual location of the structure as it is mapped in memory after alignment.

**Comment by hasherezade** [comment]
@eternaleclipse - I appreciate you taking time for testing, and thanks for your feedback!

Addressing your suggestions:
1.  I have mixed feelings about showing popups during the load, unless it is a critical error. Some people just find them annoying. But I am agree with you that the fact that sections are misaligned should be more highlighted, so this is what I did:

![added_info](https://user-images.githubusercontent.com/3115348/219683944-40973681-5435-4f5f-b938-b768beb8f613.png)

This tooltip contains various info about different PE malformations found. What do you think?

2. Regarding the "Section Hdrs" tab - this is where I display the headers literally, as is defined in the file, so I don't want to add additional fields here, as it may be misleading. I can only comment the existing fields better. I will think how to make it more clear and visible for the user.
3.  I guess you mean the conversion of the addresses is going to be invalid, and still using the old raw addresses to map? This is not the case, as it already uses the mapped addresses.

Please have look at this demo file (pass `demo_demo`): 
+ [imp1.zip](https://github.com/hasherezade/pe-bear/files/10768037/imp1.zip)

The section containing imports has been misaligned:

![misaligned_sec](https://user-images.githubusercontent.com/3115348/219690162-e97dced8-fa80-449d-92f4-f7d5f662382a.png)

It corrupts how the imports are displayed in case of the old PE-bear version:

![old_pebear](https://user-images.githubusercontent.com/3115348/219690302-c446e9df-04b2-477c-af26-97f1cf3cedf4.png)

However, the new version automatically compensates for the misalignment, and uses the offsets the way they are mapped, rather than their literal definitions:

![new_pebear](https://user-images.githubusercontent.com/3115348/219690636-810f19f6-d593-4ce5-8fd7-2640185548b5.png)

Does it answer your concerns about it? Please let me know your thoughts.

**Comment by eternaleclipse** [comment]
About the misaligned section warning - I do understand your dislike of the message box interfering with the flow of the application. A more subtle visible cue is also good. I think it's better to have something that is clearly visible at all times, for example at the status bar `"File: C:\bad.exe (WARNING: Malformed PE, contains misaligned sections)"`. That's just my preference though, I don't think there is a particularly correct way to handle it - it's a design decision.

About the pointer resolving fix - Previously, I didn't realize it applies to different pointers in all section types. I've just tested it with the misaligned imports binary you sent and it works great!

Cheers 🍻

**Comment by hasherezade** [comment]
Thank you! BTW, after trying various options, I settled with the MessageBox after all.

**Comment by hasherezade** [comment]
available in the latest release: 
+ https://github.com/hasherezade/pe-bear/releases/tag/v0.6.5
